### ISSUE TITLE
Use sunpy's FIDO to get more precise data from VSO

### ISSUE THREAD

**Issue by dpshelio** [gabgarar/Sunpy--Solar-Synoptic-Map#10]
```python
sdo_list = Fido.search(a.Time('2012/3/4', '2012/3/6'), a.Instrument('aia'),
                       a.Wavelength(171*u.angstrom), a.vso.Sample(10*u.minute)) 
downloaded_files = Fido.fetch(sdo_list)  
```
It will search and download data with the sample you define. Check [Sunpy's guide](http://docs.sunpy.org/en/stable/guide/acquiring_data/fido.html) for more details about fido.

**Comment by gabgarar** [comment]
I see a higher number of images and higher quality using Fido.search and Fido.fetch
instead of downloading them from SM.
Perfect.
