### ISSUE TITLE
Does sunpy.map doesn't read solarmonitor fits?

### ISSUE THREAD

**Issue by dpshelio** [gabgarar/Sunpy--Solar-Synoptic-Map#5]
I would imagine `sunpy.map.Map('solarmonitor.fits')` would work. It does to me with a random file from the ones you've got in the `FITS_def` directory. If this is the case, then `mappingTheImage()` function is not needed.

**Comment by gabgarar** [comment]
Changed mappingTheImage()  function by readFits()
