### ISSUE TITLE
Use more of astropy.units

### ISSUE THREAD

**Issue by dpshelio** [gabgarar/Sunpy--Solar-Synoptic-Map#7]
There are few places where you are playing with hardcoded numbers, in `astropy.units` you have units for degrees, pixels, days, etc... 

```pyhton
num_days = 24 * u.days
full_circle = 360 * u.deg
period = 25.4 * u.deg/u.day
deg_day = num_days * full_circle / period
```
you can use also the [`quantity_input`](https://docs.astropy.org/en/stable/api/astropy.units.quantity_input.html#astropy.units.quantity_input) decorator to check the functions get the right units as inputs.

**Comment by gabgarar** [comment]
Added more units to deployments
