### ISSUE TITLE
pathlib to work better with paths

### ISSUE THREAD

**Issue by dpshelio** [gabgarar/Sunpy--Solar-Synoptic-Map#8]
Python has the [pathlib module](https://docs.python.org/3/library/pathlib.html) which makes the code cleaner when working with paths:

```python
path_out = path_out / "mapa_sinaptico_.png"
```
Then you have thinks like `path_out.is_dir()` or `path_out.exists()`

**Comment by gabgarar** [comment]
I prefer to use the library os.
I ve also left the code more readable with :
if not _d.isdir(path_out):
          os.makedirs(path_out, exist_ok=True)
