### ISSUE TITLE
No need to decompress map files

### ISSUE THREAD

**Issue by dpshelio** [gabgarar/Sunpy--Solar-Synoptic-Map#9]
I believe... that `astropy.io.fits` (under the hook of `sunpy.map`) works fine with compressed files. So there's no need to decompress them.

But in case you want to do it, you can work out the extensions of files with `pathlib` (`Path(filename).suffixes`) or `os.path` (`os.path.splitext(filename)`).

**Comment by gabgarar** [comment]
Sunpy can open compressed files.
